echo ""
echo "---"
echo ""
echo "LANGAGE DU TERMINAL (UNIX) --> bash"
echo "EXTENSION DES FICHIERS BASH : .sh"
echo ""
echo "---"
echo ""
echo "LISTE DES COMMANDES APPRISES AVEC MICHAEL"
echo ""
echo -e "\tpwd --> OU JE SUIS (Path Work Directory)"
echo -e "\tls  --> QU'Y A-T'IL ?"
echo -e "\tcd [dossier-destination] --> JE ME DEPLACE"
echo ""
echo " Commandes de creation / suppression"
echo ""
echo -e "\ttouch [fichier(s)] --> Creation d'un ou plusieurs fichiers"
echo -e "\tmkdir [dossier(s)] --> Creation d'un ou plusieurs dossiers"
echo -e "\trm -rv [element(s)] --> Suppression d'un ou plusieurs elements (fichiers ou dossiers)"
echo ""
echo -e "\tmv [element(s)] [destination] --> Deplacement d'un ou plusieurs elements"
echo ""
echo " Commandes propres a Windows"
echo ""
echo -e "\tstart . --> Demarrer l'explorateur de fichier ici"
echo -e "\tnotepad [fichier] --> Ouvrir un fichier avec le bloc note"
echo ""
echo "---"
